# Configuration Jekyll minimale pour GitHub Pages
baseurl: ""
url: ""

# Désactiver Jekyll pour les fichiers statiques
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Permettre les fichiers avec des underscores
include:
  - _config.yml

# Pas de plugins Jekyll
plugins: []
